<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller;
use App\Models\PrivacyReportRequest;
use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Storage;
class PrivacyController extends Controller {
 private array $allowed=['plans','daily_plans','incomes','budgets','expenses','debts','savings_goals','savings_contributions','diet_logs','exercise_logs','sleep_logs','health_checkups','projects','project_tasks','reminders','spiritual_practices','notes','ai_plans'];
 private function map(): array {return ['plans'=>\App\Models\Plan::class,'daily_plans'=>\App\Models\DailyPlan::class,'incomes'=>\App\Models\Income::class,'budgets'=>\App\Models\Budget::class,'expenses'=>\App\Models\Expense::class,'debts'=>\App\Models\Debt::class,'savings_goals'=>\App\Models\SavingsGoal::class,'savings_contributions'=>\App\Models\SavingsContribution::class,'diet_logs'=>\App\Models\DietLog::class,'exercise_logs'=>\App\Models\ExerciseLog::class,'sleep_logs'=>\App\Models\SleepLog::class,'health_checkups'=>\App\Models\HealthCheckup::class,'projects'=>\App\Models\Project::class,'project_tasks'=>\App\Models\ProjectTask::class,'reminders'=>\App\Models\Reminder::class,'spiritual_practices'=>\App\Models\SpiritualPractice::class,'notes'=>\App\Models\Note::class,'ai_plans'=>\App\Models\AiPlan::class];}
 public function index(Request $r): JsonResponse { $u=$r->user(); return response()->json(['data'=>['deletion_requested_at'=>$u->deletion_requested_at?->toIso8601String(),'scheduled_deletion_at'=>$u->scheduled_deletion_at?->toIso8601String(),'reports'=>PrivacyReportRequest::where('user_id',$u->id)->latest()->limit(20)->get()]]); }
 public function requestReport(Request $r): JsonResponse { $d=$r->validate(['reason'=>'required|string|max:2000','modules'=>'required|array|min:1','modules.*'=>'string','date_from'=>'nullable|date','date_to'=>'nullable|date|after_or_equal:date_from']); $mods=array_values(array_intersect($d['modules'],$this->allowed)); if(!$mods)return response()->json(['message'=>'Select at least one valid module.'],422); $rr=PrivacyReportRequest::create(['user_id'=>$r->user()->id,'reason'=>$d['reason'],'modules'=>$mods,'date_from'=>$d['date_from']??null,'date_to'=>$d['date_to']??null,'status'=>'processing']); try{$payload=[];$map=$this->map();foreach($mods as $m){$q=$map[$m]::where('user_id',$r->user()->id);if($rr->date_from)$q->whereDate('created_at','>=',$rr->date_from);if($rr->date_to)$q->whereDate('created_at','<=',$rr->date_to);$payload[$m]=$q->get();}$pdf=Pdf::loadView('privacy.report',['user'=>$r->user(),'requestRow'=>$rr,'payload'=>$payload]);$path="privacy-reports/{$r->user()->id}/report-{$rr->id}.pdf";Storage::disk('local')->put($path,$pdf->output());$rr->update(['status'=>'completed','file_path'=>$path,'completed_at'=>now()]);try{Mail::raw('Your requested My Digital Diary personal data report is attached.',function($mail)use($r,$path){$mail->to($r->user()->email)->subject('Your Personal Data Report')->attachData(Storage::disk('local')->get($path),'my-digital-diary-data-report.pdf',['mime'=>'application/pdf']);});}catch(\Throwable $e){report($e);} }catch(\Throwable $e){$rr->update(['status'=>'failed','error_message'=>$e->getMessage()]);return response()->json(['message'=>'Could not generate report.'],500);} return response()->json(['message'=>'Report generated and emailed.','data'=>$rr->fresh()]); }
 public function scheduleDeletion(Request $r): JsonResponse { $d=$r->validate(['password'=>['required','current_password'],'reason'=>'required|string|max:2000','backup'=>'nullable|boolean','confirm_delete'=>'accepted']);$u=$r->user();if((bool)($d['backup']??false)){$payload=['exported_at'=>now()->toIso8601String(),'profile'=>$u->only(['id','name','email','phone','created_at'])];foreach($this->map() as $key=>$class){$payload[$key]=$class::where('user_id',$u->id)->get()->toArray();}$json=json_encode($payload,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);try{Mail::raw('Your complete My Digital Diary backup is attached. Keep it in a safe place.',function($mail)use($u,$json){$mail->to($u->email)->subject('Your My Digital Diary Backup')->attachData($json,'my-digital-diary-backup.json',['mime'=>'application/json']);});}catch(\Throwable $e){report($e);}}$u->update(['deletion_reason'=>$d['reason'],'deletion_requested_at'=>now(),'scheduled_deletion_at'=>now()->addDays(30)]);return response()->json(['message'=>'Account scheduled for permanent deletion in 30 days.','scheduled_deletion_at'=>$u->fresh()->scheduled_deletion_at?->toIso8601String()]); }
 public function cancelDeletion(Request $r): JsonResponse {$r->user()->update(['deletion_reason'=>null,'deletion_requested_at'=>null,'scheduled_deletion_at'=>null]);return response()->json(['message'=>'Account deletion cancelled.']);}
}
