<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * The standard Laravel notifications table — required for the `database`
 * notification channel to work at all (SubscriptionExpiryReminderNotification
 * uses it, alongside `mail`, for the in-app "notification upon login"
 * requirement). Normally generated by running
 * `php artisan notifications:table`, but that was never run on this
 * project, so this is that exact same migration written by hand.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('notifications', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->string('type');
            $table->morphs('notifiable');
            $table->text('data');
            $table->timestamp('read_at')->nullable();
            $table->timestamps();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('notifications');
    }
};
