<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Social Media Post Report</title>

    @include('social-media-planner.partials.report-styles')

    <style>
        @page {
            margin: 24px 28px;
        }

        body {
            margin: 0;
            font-family: DejaVu Sans, sans-serif;
            color: #172033;
            font-size: 10px;
        }

        .pdf-header {
            padding-bottom: 14px;
            margin-bottom: 16px;
            border-bottom: 2px solid #0f766e;
        }

        .pdf-title {
            margin: 0;
            font-size: 20px;
            font-weight: 900;
        }

        .pdf-subtitle {
            margin-top: 4px;
            color: #64748b;
            font-size: 10px;
        }

        .pdf-grid {
            width: 100%;
            border-collapse: separate;
            border-spacing: 8px;
            margin: 0 -8px 12px -8px;
        }

        .pdf-grid td {
            width: 25%;
            vertical-align: top;
        }

        .pdf-section {
            margin-top: 16px;
            margin-bottom: 7px;
            font-size: 13px;
            font-weight: 900;
        }

        .pdf-footer {
            margin-top: 18px;
            padding-top: 8px;
            border-top: 1px solid #e2e8f0;
            color: #64748b;
            font-size: 8px;
        }

        .smr-icon {
            display: none;
        }

        .smr-value {
            font-size: 18px;
        }

        .smr-card {
            border-radius: 8px;
            padding: 10px;
        }
    </style>
</head>
<body>
@php
    $s = $report['summary'] ?? [];
    $analytics = $report['analytics'] ?? [];
    $posts = $report['posts'] ?? collect();

    $cards = [
        ['Total Posts', $s['total_posts'] ?? 0, 'smr-teal'],
        ['Published', $s['published'] ?? 0, 'smr-emerald'],
        ['Scheduled', $s['scheduled'] ?? 0, 'smr-amber'],
        ['Ready to Post', $s['ready_to_post'] ?? 0, 'smr-sky'],
        ['Views', $analytics['total_views'] ?? 0, 'smr-blue'],
        ['Reach', $analytics['total_reach'] ?? 0, 'smr-violet'],
        ['Impressions', $analytics['total_impressions'] ?? 0, 'smr-blue'],
        ['Likes', $analytics['total_likes'] ?? 0, 'smr-rose'],
        ['Engagement %', number_format((float) ($analytics['engagement_rate'] ?? 0), 2).'%', 'smr-emerald'],
    ];
@endphp

<div class="pdf-header">
    <h1 class="pdf-title">Social Media Post Report</h1>
    <div class="pdf-subtitle">
        {{ config('app.name', 'My Digital Diary') }}
        ·
        {{ $report['period_start'] ?? '—' }}
        —
        {{ $report['period_end'] ?? '—' }}
    </div>
</div>

<table class="pdf-grid">
    @foreach(array_chunk($cards, 4) as $row)
        <tr>
            @foreach($row as [$label, $value, $class])
                <td>
                    <div class="smr-card {{ $class }}">
                        <div class="smr-value">{{ $value }}</div>
                        <div class="smr-label">{{ $label }}</div>
                    </div>
                </td>
            @endforeach
        </tr>
    @endforeach
</table>

<div class="pdf-section">Post History</div>

<table class="smr-table">
    <thead>
        <tr>
            <th>Post</th>
            <th>Platforms</th>
            <th>Status</th>
            <th>Scheduled</th>
            <th>Posted</th>
        </tr>
    </thead>

    <tbody>
        @forelse($posts as $post)
            <tr>
                <td>
                    <strong>{{ $post->title }}</strong>
                    @if($post->caption)
                        <div class="smr-muted">
                            {{ \Illuminate\Support\Str::limit($post->caption, 120) }}
                        </div>
                    @endif
                </td>

                <td>
                    {{ collect($post->platforms ?? [])
                        ->map(fn($x) => ucwords(str_replace('_', ' ', $x)))
                        ->join(', ') }}
                </td>

                <td>
                    {{ $post->status === 'ready_to_share'
                        ? 'Ready to Post'
                        : ucwords(str_replace('_', ' ', $post->status)) }}
                </td>

                <td>
                    {{ optional($post->scheduled_at)->format('d M Y H:i') ?: '—' }}
                </td>

                <td>
                    {{ optional($post->published_at)->format('d M Y H:i') ?: '—' }}
                </td>
            </tr>
        @empty
            <tr>
                <td colspan="5">No posts found for this report.</td>
            </tr>
        @endforelse
    </tbody>
</table>

<div class="pdf-footer">
    Generated by {{ config('app.name', 'My Digital Diary') }}
    on {{ now()->format('d M Y, H:i') }}.
</div>
</body>
</html>
